image: node:20.9.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - bun.lockb
      prefix: npm
    paths:
      - node_modules/
  script:
    - bun install --production
    - bun --filter './playground' build
    - cp -a lib/dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
