name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: bun install --production

      - name: Build FE
        run: bun --filter './playground' build:ci

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: lib/dist
